### ISSUE TITLE
SHADE and FILL plots wrong when long time axis in units of seconds

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1009]
**Reported by @AnsleyManke on 3 May 2010 22:11 UTC**
This bug is present in all available versions of Ferret.

Coordinates are passed to PPLUS 2D plot commands in single-precision arrays. It seems that when the units of the axis is seconds, the numbers can have too many digits and somewhere a loss of precision is causing the colors to be drawn in the wrong location wrt the time axis.

Prompted by this email, 
http://www.pmel.noaa.gov/maillists/tmap/ferret_users/fu_2010/msg00272.html

But here is a simple example constructed with axes defined in Ferret.
```
! Define an axis with timesteps of 1 minute, 
! units of seconds, with origin in 1970.
! Define a 2D variable using this axis.


yes? define axis/t=1-feb-2010:3-feb-2010:3600/\\
units=seconds/t0=1-jan-1970 tsec1970
yes? define axis/z=1:100:5/depth zaxis
yes? let ztvar1970 = L[gt=tsec1970] *z[gz=zaxis]

! The color boxes drawn on the plot are shifted over by several hours.
yes? set view upper
yes? shade ztvar1970

! Now define an axis whose time origin is 
! in the same year as the data.

yes? define axis/t=1-feb-2010:3-feb-2010:3600/\\
units=seconds/t0=1-jan-2010  tsec2010
yes? let ztvar2010 = L[gt=tsec2010] + 100*z[gz=zaxis]

! The plot is correct.
yes? set view lower
yes? shade ztvar2010

yes? frame/file=time_seconds.gif
```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1737

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 3 May 2010 22:14 UTC**
Here is the example script, with formatting...


```
! Define an axis with timesteps of 1 minute, 
! units of seconds, with origin in 1970. 
! Define a 2D variable using this axis.

yes? define axis/t=1-feb-2010:3-feb-2010:3600/\\
 units=seconds/t0=1-jan-1970 tsec1970 
yes? define axis/z=1:100:5/depth zaxis 
yes? let ztvar1970 = L[*z[gz=zaxis](gt=tsec1970])

! The color boxes drawn on the plot are shifted 
! over by several hours. 
yes? set view upper yes? shade ztvar1970

! Now define an axis whose time origin is 
! in the same year as the data.

yes? define axis/t=1-feb-2010:3-feb-2010:3600/\\ 
units=seconds/t0=1-jan-2010 tsec2010 
yes? let ztvar2010 = L[+ 100*z[gz=zaxis](gt=tsec2010])

! The plot is correct. 
yes? set view lower 
yes? shade ztvar2010

yes? frame/file=time_seconds.gif 

```

**Comment by karlmsmith** [comment]
**Attachment from ansley.b.manke on 3 May 2010 22:11 UTC**

REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_1737_GIT_1009/time_seconds.gif

**Comment by karlmsmith** [comment]
Fix and bench test plots pushed to GitHub commit f528eee47ec4c38ea22a69f55f3939e2f94d8f5b
Fix also merge to PyFerret and pushed to GitHub

**Comment by AnsleyManke** [comment]
Further fixes are checked in for overlays of polygons on high-resolution time axes.

**Comment by karlmsmith** [comment]
Pushed to GitHub https://github.com/NOAA-PMEL/Ferret/commit/a9d4119c78f7b53a5904b2e7e7d5de5da05a85a1
Merged into PyFerret

**Comment by ACManke** [comment]
This bug was not fully fixed with existing check-ins for this ticket and the additional report in #1888.

Ned Cokelet reported a further instance of this kind of behavior with a 2-D dataset in time vs Z, where the observations are in 2021, and the time axis is in seconds since 1-jan-1970.  This is a time description used in modern observational datasets, but not envisioned in early Ferret development.

The time scaling that was done to fix this bug is correct but was not applied correctly in routines box_centers.F and box_bounds.F . Fixes are made in those routines and there are changes as well as axis_format.F and pltit.F.  This is tested with various time origins for time in seconds, for different plot types, and for plots where time is on the vertical axis.

I will create a pull request for this fix from my fork at https://github.com/ACManke/PyFerret
