### ISSUE TITLE
file/form=stream/type=  does not keep the type as a property of the file

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1388]
**Reported by @AnsleyManke on 12 Dec 2013 23:38 UTC**
See #2115.  

This command will read the variables from both files with /type=r8:

```

file/form=stream/type=r4/grid=data/var=a "a.dat"
file/form=stream/type=r8/grid=data/var=b "b.dat"
list a[d=1], b
```

and this will read a.dat as r4 and b.dat as r8:

```
file/form=stream/type=r4/grid=data/var=a "a.dat"
load a
file/form=stream/type=r8/grid=data/var=b "b.dat"
list a[d=1], b
```

There is not a data structure that stores the stream-read-type so when a second file is initialized its type setting is applied to any subsequent read from a binary file, but there should be.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2116

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 13 Dec 2013 00:45 UTC**
Unless anyone has an objection I'm making this low priority. It's unexpected behavior and not typical of how Ferret handles things, but it would require either a new data structure for all datasets, or some modest changes to the old C code that handles binary file reading.  As it's been the behavior without apparently causing confusion for all of Ferret's history, I would like to leave it alone.

**Comment by AnsleyManke** [comment]
We had another request from the users list for setting the data type when writing stream binary files. This isn't something we want to spend a lot of time supporting but since we have the syntax LIST/OUTTYPE= for netCDF files, it's an hour's work to allow this for stream binary files as well.

We will not keep track of the input data type of data read in from stream binary files, but will allow the user to specify the output data ype

list/format=stream/outtype=FLOAT ...

with the types being DOUBLE, FLOAT, INT, SHORT, BYTE as in netCDF-writing

We've been saying for years that we should say that the capabilities for working with these file types are deprecated.  I'll note in the documentation that stream binary and unformatted files are "not actively supported".

**Comment by AnsleyManke** [comment]
This is done, and a bit of new testing added to the bn_test_stream.jnl
