### ISSUE TITLE
SHADE and CONTOUR color key edges and centers with /KEY=CENTERLAB

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1607]
**Reported by @AndrewWittenberg on 10 Dec 2015 17:50 UTC**
The documentation at

http://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/commands-reference/CONTOUR#_VPINDEXENTRY_1265

says:

```CONTOUR/FILL/KEY=CENTERLAB```

''Labels the color key in the colored sections of the key rather than at the default location at the line dividing one color from the next. The levels controls do not change for this style, only the locations of the labels.''

Now with ```/KEY=CENTERLAB``` the labels shift to the center of the color patches, and the number of color patches increases by one.  Seems almost right, but check this out.

First set up a field with values of 0.5, 1.5, 2.5 etc. in cells spanning (0,1), (1,2), (2,3) etc.:

```
 	NOAA/PMEL TMAP
 	FERRET v6.961 (beta)
 	Linux 2.6.32-573.8.1.el6.x86_64 64-bit - 12/09/15
 	10-Dec-15 11:36     

yes? def ax/edge/x=0:10:1 xax; let a = x[gx=xax] + 0*y[gy=1:9:1]
```

Now watch what CENTERLAB does:

```
yes? cancel view; set view ul; shade/line/lev=(0,10,2)/key/title="/KEY" a
yes? set view ur; shade/line/lev=(1,9,2)/key=centerlab/title="/KEY=CENTERLAB" a
```

The upper-left plot is fine; between any two contours the cell-values lie entirely within each contour interval.

But the upper-right plot with ```/KEY=CENTERLAB``` is a little strange.  The color key is misleading, since it suggests that the value of "3" sits at the midpoint of the teal-colored patch, while the plot shows that it actually sits at the lower edge.

Two ways to address this:

1) Interpolate between the /LEVELS values to obtain new '''edge-values''' for the contours and patch-edges; then SHADE and CONTOUR just as we always have, but using those new computed levels.  The color key would labeled at the patch-centers using the original /LEVELS values.  Or

2) Interpolate between the /LEVELS values to obtain new '''patch-center values''' applied as labels for the color key; then SHADE and CONTOUR just as we always have using the original /LEVELS values.

Perhaps these 2 alternatives could be added as options, e.g. something like (1) "/KEY=CENTERLAB(COMPUTE_EDGES)" and (2) "/KEY=CENTERLAB(FROM_EDGES)".  The results would look like the bottom 2 panels on the plot, generated artificially in Ferret v6.961 with:

```
yes? set view ll; shade/lev=(1,9,2)/key=centerlab/title="/LEV=(1,9,2)/KEY=CENTERLAB(COMPUTE_EDGES)" a; shade/ov/nolab/nokey/line/lev=(0,10,2)/key a
yes? set view lr; shade/lev=(1,9,2)/key=centerlab/title="/LEV=(0,10,2)/KEY=CENTERLAB(FROM_EDGES)" a; shade/ov/nolab/nokey/line/lev=(0,10,2)/key a
```

I'd suggest making (1) the default for CENTERLAB, since integer fields are probably the main application for CENTERLAB.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2335

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 10 Dec 2015 18:00 UTC**
Thanks, I'll study this.  The intent here is to make a correct key for data such as "vegetation index" where the values are discrete and blue should be index 1, green is index 2, etc.

**Comment by karlmsmith** [comment]
**Attachment from andrew.wittenberg on 10 Dec 2015 17:51 UTC**
The resulting plot.
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_2335_GIT_1607/plot.gif

**Comment by AnsleyManke** [comment]
I am implementing option 1 suggested in the original report.  The effect is that the values given by the /LEVELS specification will be the numbers used to label the colors on the colorbar instead of the boundary between colors (the location of contour-lines on a color-fill contour plot).  For discrete colors in particular I think this is what is expected. So for instance to color by a flag, which may take on the values 2-5 or 9, it would be:

  PLOT/VS/LEV=(2,5,1)(9)/palette=ten_by_levels  xpts, ypts, flag

Plots like the example above now looks like this -- the upper two are the same plot with differently-labeled colorbars, the lower one shows the effect of keeping the same levels spec but changing to /KEY=center

```
yes? def ax/edge/x=0:10:1 xax
yes? let a = x[gx=xax] + 0*y[gy=1:9:1]

yes? set v ul; shade/line/lev=(0,10,2)/key/title="/KEY/LEV=(0,10,2)" a
yes? set v ur; shade/line/lev=(1,9,2)/key=centerlab/title="/KEY=CENTERLAB/LEV=(1,9,2)" a
yes? set v ll; shade/line/lev=(0,10,2)/key=centerlab/title="/KEY=CENTERLAB/LEV=(0,10,2)" a
```
![centerlab](https://user-images.githubusercontent.com/5122690/38157350-0590cde8-343b-11e8-8f13-d3a491310b8d.gif)


If FILL/LINE or SHADE/LINE is given as in these examples, the lines will always be drawn as contour lines between colors.

A new symbol is added to the automatically-generated  LEV* symbols. Symbol lev_centered_labels takes the value "on" or "off"

```
yes? shade/line/lev=(1,9,2)/key=centerlab/title="/KEY=CENTERLAB/LEV=(1,9,2)" a
yes? show sym lev*
LEV_TEXT = "(1,9,2)"
LEV_MIN = "0"
LEV_MAX = "10"
LEV_NUM = "5"
LEV_DEL = "2"
LEV_CENTERED_LABELS = "on"
```
