### ISSUE TITLE
graticule lines lost with overlays

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1786]
**Reported by @AnsleyManke on 8 Mar 2017 22:10 UTC**
Martin Schmidt reported this, and we see it with LAS plots. 
http://www.pmel.noaa.gov/maillists/tmap/ferret_users/fu_2017/msg00048.html

This goes back a ways. Starting with the fix to #2279, we draw axis lines only on the first plot, to prevent over-thickening of lines when drawing with PyFerret. Previously, axes were re-drawn on overlays, to make sure that things like tic marks and graticule lines weren't obscured when overlays were drawn. 

Ferret example:

```
yes? use coads_climatology
yes? shade/l=1/graticule=(color=blue) sst
yes? fill/over/l=1 sst
yes? go fland 20 gray
```

The graticule lines are visible only in places where there is no data in SST and no land.

Perhaps graticule lines, and maybe also tic marks, but not the axis lines, should be re-drawn with each overlay.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2514

**Comment by AnsleyManke** [comment]
If we drew graticule lines on all overlays, then those graticule lines would get thicker and thicker in PyFerret plots where they show up.  I think the best answer is to allow the user coltrol when to plot graticules -- which are part of axis-line drawing -- on an overlay, so that for a high-quality plot, we would remove axes from all of the layers except the last thing overlaid.  As things stand now, /OVERLAY on a plotting command causes us to never draw axes or graticule lines. 

The new behavior will be that /OVERLAY/AXES will draw the axes and any graticules that have been defined.

 So,

```
yes? shade/noaxes my_var
yes? set mode graticule
yes? fill/overlay/nolabel/AXES my_var
```

Often the last thing drawn is the land masses using the fland.jnl script

```
yes? shade/noaxes my_var
yes? fill/overlay/nolabel my_var
yes? go fland  
```

If there are graticules, then we want the graticule lines on top of the land masses.  The fland.jnl script could by default make plot axes. It could have a new option to control whether axis/graticule lines are drawn.

I have checked in the use of /OVERLAY/AXES as a combination, and am closing this ticket. We may want to revisit this as we work with it.``
