### ISSUE TITLE
@std on modulo axis: answers change and/or fail, starting in v7.11

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1849]
Create a monthly variable for years 401-402, regrid to climatological monthly axis, then compute stddev using a couple of different explicit limits.  In v7.1 and earlier we get:

```
 	NOAA/PMEL TMAP
 	FERRET v7.1 (optimized)
 	Linux 2.6.32-642.6.1.el6.x86_64 64-bit - 02/16/17
 	19-Dec-17 22:58     

yes? def ax/t/edge/unit=day/mod=365.2425/t0=1-jan-0001 tax_c = {0,31,59.2425,90.2425,120.2425,151.2425,181.2425,212.2425,243.2425,273.2425,304.2425,334.2425,365.2425}
yes? def ax/t/edge/unit=day/t0=1-jan-0001 tax = {146097,146128,146156,146187,146217,146248,146278,146309,146340,146370,146401,146431,146462,146493,146521,146552,146582,146613,146643,146674,146705,146735,146766,146796,146827}
yes? let a = sin(t[gt=tax])
yes? let a_c = a[gt=tax_c@mod]
yes? list a_c[t=1-jan-0301:1-jan-0302@std]
             VARIABLE : A[GT=TAX_C@MOD]
             TIME     : 01-JAN-0301 00:00 to 01-JAN-0302 00:00 (standard deviation)
          0.7138
yes? list a_c[t=1-jan-0401:1-jan-0402@std]
             VARIABLE : A[GT=TAX_C@MOD]
             TIME     : 01-JAN-0401 00:00 to 01-JAN-0402 00:00 (standard deviation)
          0.7138
```

But in v7.11 - v7.3 we get:

```
 	NOAA/PMEL TMAP
 	FERRET v7.3 (optimized)
 	Linux 2.6.32-696.16.1.el6.x86_64 64-bit - 12/04/17
 	19-Dec-17 23:06     

yes? list a_c[t=1-jan-0301:1-jan-0302@std]
             VARIABLE : A[GT=TAX_C@MOD]
             TIME     : 01-JAN-0301 00:00 to 01-JAN-0302 00:00 (standard deviation)
          0.6974
yes? list a_c[t=1-jan-0401:1-jan-0402@std]
             VARIABLE : A[GT=TAX_C@MOD]
             TIME     : 01-JAN-0401 00:00 to 01-JAN-0402 00:00 (standard deviation)
        ....
```

In the first case the answer has changed, and in the second case we get a "bad" result!  Why?

v7.11 was when the new memory management came in -- is it related to that?

Rating this as high priority, since it's causing some of our automated diagnostics to fail.  I hadn't noticed this earlier, since I hadn't been using explicit limits with years this far past the T0 year.

**Comment by AnsleyManke** [comment]
The error is definitely related to all of the changes prior to new memory management and splitting calculations along the dimension of the transformation.   No splitting/gathering is being done here of course, but the calculation is done differently.

The missing-value in the second calculation comes from a pure bug; the portions of the grid cell boxes are slightly different for the two years.  Because of leap years, Jan 1,0401 lies right at the edge of a box, but Jan 1,0301 does not. Try this to see it:
```
set list/precision=10
list/t=1-jan-0301:1-jan-0302 tbox[gt=a_c], tboxlo[gt=a_c]
list/t=1-jan-0401:1-jan-0402 tbox[gt=a_c], tboxlo[gt=a_c]
```

so in the weighted calculation box sizes are computed between the two dates given, with possible partial boxes at the edges.  The first partial box in the  0401-0402 calculation is exactly 0 but there's a small non-zero partial box starting the 0301-0302 calculation.  The zero-box size was not being handled correctly, resulting in a divide by zero. Easy enough to fix this much of it.

**Comment by AnsleyManke** [comment]
The difference in the computed results is because a new algorithm is used, which lets the result be accumulated in what might be several chunks for a large grid. In previous versions of Ferret there's a 2-step calculation of variance or STD.  I think that the current calculation is correct and the previous one from older versions was not doing a correct calculation where grid-box sizes at the ends of the time interval may be zero.  There is a box size of zero when the date given exactly corresponds to the grid box edge.

The prior method was in two steps: 1) compute a weighted mean, using the box sizes, 2) in the second pass there is a count n=# steps.  This count is incremented even if the box size is 0.  If (in a copy of the v7.1 code) I change the logic to increment the count only when the grid box size is positive, I get the same result as we see in v7.3. 
 
To further explore this, try defining evenly-spaced axes using the 360-day calendar
```
 
def ax/t/edge/unit=day/mod=360/t0=1-jan-0001/calendar=d360 tax360_c = {0,30, 60, 90,120,150,180,210,240,270,300,330,360}
def ax/t/edge/unit=day/t0=1-jan-0001/calendar=d360 tax360 = 144000 + \
{0,30,60,90,120,150,180,210,240,270,300,330,360,390,420,450,480,510,540,570,600,630,660,690,720}

let b = a[gt=tax360@asn] ! same numerical values
let b_c = b[gt=tax360_c@mod]
```
Both Ferret v7.1 and 7.3 get this result:
```
list b_c[t=1-jan-0301:1-jan-0302@std]
             VARIABLE : B[GT=TAX360_C@MOD]
             TIME     : 01-JAN-0301 00:00 to 01-JAN-0302 00:00 (standard deviation) 360_DAY
          0.7003
list b_c[t=1-jan-0401:1-jan-0402@std]
             VARIABLE : B[GT=TAX360_C@MOD]
             TIME     

```

The method used in v7.3 is in the https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance 

```
def weighted_incremental_variance(dataWeightPairs):
    wSum = wSum2 = mean = S = 0

    for x, w in dataWeightPairs:  # Alternatively "for x, w in zip(data, weights):"
        wSum = wSum + w
        wSum2 = wSum2 + w*w
        meanOld = mean
        mean = meanOld + (w / wSum) * (x - meanOld)
        S = S + w * (x - meanOld) * (x - mean)

    population_variance = S / wSum

```

Previously to Ferret v7.11, the method used is the on-line method in the same page, where the mean has been computed.

I am closing this  - am happy to look further if necessary

**Comment by karlmsmith** [comment]
Pushed to GitHub  in commit https://github.com/NOAA-PMEL/Ferret/commit/4e5023d9fc2e9e600b5aa562f9732b473bb9f0a7
Merged into PyFerret and pushed to GitHub.

**Comment by AndrewWittenberg** [comment]
Yes, this looks correct now.  Starting from the original example, let's compute the stddev two different ways, and compare to what Ferret gives us:

```
yes? let adev2 = (a_c - a_c[t=1-jan-0301:1-jan-0302@ave])^2
yes? let a2 = a_c^2

yes? list/p=9/t=1-jan-0301:1-jan-0302 a_c[t=@std], adev2[t=@ave]^.5, (a2[t=@ave]-a_c[t=@ave]^2)^.5
                  A_C      EX#2         EX#3
I / *:     0.697446363  0.697446363  0.697446363
```

They all agree.  Fabulous!
