### ISSUE TITLE
region affects contour label precision, even if contour spacing is specified

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1858]
Changing the region affects the default precision of contour labels, even if the contour spacing is specified:

```
 	NOAA/PMEL TMAP
 	PyFerret v7.31 (beta/optim)
 	Linux 2.6.32-696.16.1.el6.x86_64 - 12/27/17
 	30-Jan-18 20:52     

yes? use coads_climatology
yes? set view left; contour/l=1/lev=1d sst
yes? set view right; contour/l=1/x=120e:80w/y=20s:20n/lev=1d sst
```

The left panel looks good, with integer precision appropriate for the integer contour spacing.  But the right panel has an unnecessary extra digit of precision, even though we've specified the same contour spacing as in the left panel.

![plot](https://user-images.githubusercontent.com/34082818/35601559-be1fb8dc-0601-11e8-85dd-87c700724a77.png)

**Comment by AnsleyManke** [comment]
And the extra digit of "precision" is consistently adding a .0 which doesn't even add any information.

**Comment by AnsleyManke** [comment]
This is one of those cases where automatic settings don't quite get things right.  Just the fact that the second plot has fewer levels means a different setting for the formatting of the numbers gets chosen.  I've added a further simple test, so that auto levels with integer values and integer delta will be labeled with integers (!)
