### ISSUE TITLE
Data plotted outside plot area

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1859]
Not sure if this is a Ferret issue or LAS Ferret scripts in SOCAT issue.
Salinity exists for only the first few points in the SOCAT dataset 33BI20160827.
[33BI20160827.nc.zip](https://github.com/NOAA-PMEL/Ferret/files/1690485/33BI20160827.nc.zip)

With the latest SOCAT LAS using the latest Ferret (v7.3.1), the salinity thumbnail, as well as the correlation viewer plot, has a point that is plotted outside the plot area.
<img width="702" alt="33bi20160827_thumbnails" src="https://user-images.githubusercontent.com/16406727/35749990-48bb57c8-0808-11e8-89f5-97defdd75926.png">

In older SOCAT LAS using Ferret 7.3, the salinity plot is within the plot and actually has some extra whitespace around the plot.
<img width="694" alt="33bi20160827_thumbnails_ferret73" src="https://user-images.githubusercontent.com/16406727/35750156-eab3caba-0808-11e8-9c81-ae28ef31df8c.png">

**Comment by karlmsmith** [comment]
Just realized that most of the new thumbnail plots do not have Y-axis labels.  (Some not shown here do have the fCO2_recommended label.)  Not sure if that was intentional or not.  Since the hover help explains the plot, figuring the lack of labels is not a major problem.

**Comment by AnsleyManke** [comment]
This is all in the Ferret scripts for LAS - not particularly specific to SOCAT, but just in setting up thumbnail and property-property plots with time as the horizontal axis.

The symbol getting plotted outside the plot box is due to an extra short time axis, as the Salinity variable for this trajectory only has a few valid data points; the time axis being defined for an underlay plot that draws the axes was not quite right.

The vertical axes should be labeled, just as they are for non-time plots - the thumbnails have one plot that's fco2_rec as a function of temperature, and that has labels.  I have added those labels back to the plots.

All of this is checked in to git, so will need to be gotten over to svn and the socat_latest branch.
