### ISSUE TITLE
Applying unpacked _FillValue with packed values

### ISSUE THREAD

**Issue by marceloandrioni** [NOAA-PMEL/Ferret#1861]
I have a file with packed values like this:

        short ssh(time, latitude, longitude) ;
                ssh:_FillValue = -30000s ;
                ssh:long_name = "Water Surface Elevation" ;
                ssh:standard_name = "sea_surface_elevation" ;
                ssh:units = "m" ;
                ssh:NAVO_code = 32 ;
                ssh:add_offset = 0. ;
                ssh:scale_factor = 0.001 ;

When plotting with Ferret I noticed some blank areas near the coast (image bellow). Checking the values with list also showed then as missing (...). I tried plotting the same file with python, matlab and ncview and it showed just fine.
Checking the file directly (without using Ferret), I saw that Ferret was blanking cells with value -0.03.  This value when stored packed in the file is -30 (-30 * scale_factor=-0.03, where scale_factor=0.001). My guess for the problem is that Ferret is unpacking the _FillValue (-30000 * 0.001=-30) and removing these values from the still packed values (when -0.03 is still represented by -30).

According to [https://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html](url):
"If the variable is packed using scale_factor and add_offset attributes (see below), the _FillValue attribute should have the data type of the packed data." From that I think I am correct in using _FillValue = -30000.

I am using Ferret v7.3 but tested with 6.9 and the same thing happened.

Thank you very much

![ferret_ssh](https://user-images.githubusercontent.com/13545615/36323450-24e13422-1338-11e8-9d63-6ea643d66897.png)

**Comment by AnsleyManke** [comment]
In the conventions for handling of missing data,
http://cfconventions.org/cf-conventions/cf-conventions.html#missing-data

... The missing values of a variable with scale_factor and/or add_offset attributes (see Section 8.1, "Packed Data") are interpreted relative to the variable’s external values (a.k.a. the packed values, the raw values, the values stored in the netCDF file), not the values that result after the scale and offset are applied. Note that values that are identified as missing should not be transformed.  ... 

So, what we should do, is look at the packed data, and treat all values that are -30000s as missing, and scale everything else. 

Because Ferret stores and works with data internally is double-precision, some difficulties in numeric precision come up when working with the scale factor and it's inverse when we go to re-pack the data if it's written out to a new file.  We have been in fact converting the _FillValue to its equivalent unpacked value and using that internally; if the data is written out to a new netCDF file, we re-pack it all.  So long as the range of values in the unpacked data values doesn't overlap with the "unpacked" missing value, this is accurate.  

Your example shows that this is not the right way to handle this, and we'll change it so that we mark the data that's missing without converting the _FillValue.

**Comment by marceloandrioni** [comment]
Ok, thank you for the info. I am glad to know this will be addressed in future releases. Just to clarify, I created the file using python (xarray and netcdf4) and not Ferret, so the packing was done entirely outside Ferret. My problem is only with visualization, I don't know if creating the file in Ferret would result in the same problem or not. Thanks.

**Comment by AnsleyManke** [comment]
I think if you created the file with the same missing-value and packing with Ferret, it would behave in the same way.  Often when packing data, people use the maximum or minimum value of a short integer, 32767 or -32767 as the _FillValue. As a workaround until we have this fixed, if you used one of those values, its scaled equivalent would not conflict with valid values and you wouldn't get this effect.

**Comment by marceloandrioni** [comment]
Thank you for the suggestion, using -32767 as the _FillValue solved the problem (image bellow). I was using -30000 because that was the original value used in the global dataset available in the HYCOM Consortium Opendap, but using a _FillValue that can't possibly exist in the packed values it's a good idea.

![ferret_fill32767](https://user-images.githubusercontent.com/13545615/36444003-2294ac52-1659-11e8-8abc-e8d292f6de54.png)

**Comment by AnsleyManke** [comment]
This is fixed - we now skip and do not unpack any missing_data or _FillValue flags.

There is a change in the benchmark output, case 19 in bn_attributes.jnl now lists correct data in the ncdump output for packed data.
