### ISSUE TITLE
USE of a numeric-named NetCDF file (neglecting extension) crashes Ferret

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1887]
This may be related to #540.  I got a crash when trying to use a dataset named "1979-2010.nc" but without the extension:

```
 	NOAA/PMEL TMAP
 	FERRET v7.42 (optimized)
 	Linux 2.6.32-754.el6.x86_64 64-bit - 07/10/18
 	26-Jul-18 13:48     

yes? use 1979-2010
At line 541 of file xeq_set.F
Fortran runtime error: Bad integer for item 1 in list input
```

But the following works fine:

```
yes use 1979-2010.nc
```

So we just need to handle that first case more gracefully.

**Comment by AnsleyManke** [comment]
yes, this should be a relatively simple thing to test for in the parsing steps that are detecting this.

**Comment by AnsleyManke** [comment]
The test whether this is a "USE n", to change the default dataset to dataset number n, was mistakenly deciding that  1979-2010 was a number, rather than just a name to go hunt for in the dataset path directories.

In addition, filenames like  2016.07.nc would previously have crashed Ferret, if the user said

yes? use 2016.07

That's fixed as well, xeq_set.F, and some tests added.
