### ISSUE TITLE
Plotted time axis extends past right plot edge

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1920]
Using the the script
```
USE EXPT20171217_decimated.nc
DEFINE AXIS/T/T0="1-Jan-1970"/UNITS=seconds tax = time
LET tt = t[gt=tax]
LET/TITLE=Longitude lon = RESHAPE(longitude, tt)
PLOT lon
FRAME /FILE=lon_vs_time.gif
```
with either Ferret or PyFerret gives a time axis that plots too far:
![lon_vs_time](https://user-images.githubusercontent.com/16406727/55108064-fd327a80-508f-11e9-874c-ed8fe32a528c.gif)

Data file used goes to Dec 27 00:00:01
Data file and script in:
[lon_vs_time.zip](https://github.com/NOAA-PMEL/Ferret/files/3015065/lon_vs_time.zip)

**Comment by karlmsmith** [comment]
Also, the little black square at the bottom right corner of the plot.  Wei had seen this as well in her plots.  It appears on displayed Ferret plots but not with -gif option.  (Wei was happy with that solution.)  It does not happen in PyFerret, so maybe just an artifact of X-Windows and not something to worry about.

**Comment by karlmsmith** [comment]
The extended time axis problem appears in 7.2.1 but not 7.1

The little black square appears to be an artifact of XQuartz on the Mac, so forget about that one.

**Comment by AnsleyManke** [comment]
The appearance of this at v7.2 was due to getting shorter interval time plots working, labeled down to minutes and seconds.  

Note that some of it has been happening all along with older versions even going back to pre-double-precision Ferret.

```
yes? define axis/t=1-jan-1990:20-jan-1990:1/units=seconds/t0=1-jan-1990 taxis
yes? let tt = t[gt=taxis]
yes? plot/nolab/color=blue/t="2-jan-1990:23:59:50":"12-jan-1990:00:00:10" cos(tt/40000)
```
It's never been frequent, because users wouldn't often ask for a time range extending just a few seconds into the next day, but  when using discrete datasets and defining time axes from time data from the file, this kind of thing would likely crop up more often.  Good to get it worked out.

The fix is in pplldx.F, using double-precision computations for the time range, but only for the time axis styles when the time axis range is small. Also an adjustment in fixtim.F where we want to re-compute the date-string itnew2 when there are nonzero seconds; where previously it only looked at the hours and minutes.
