### ISSUE TITLE
time_origin truncated

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1933]
In Ferret 7.4.4.1 but not in 7.4.3.2, the time_origin attribute on a time axis is getting truncated losing the last digit of the year.  Simultaneously, the single-digit day becomes zero-prefixed two-digit day.  (`1-JAN-1970` becomes `01-JAN-197`)
This can be seen from the script:
```code
LET ii = _I[I=1:24]
LET offset1970 = DAYS1900(1970,1,1)
LET month = MOD(ii-1,12)+1
LET year = 1970 + INT((ii-1)/12)
DEFINE AXIS/T0="1-JAN-1970"/EDGES/UNITS=days tmnth = DAYS1900(year,month,1) - offset1970
LET mytime = _T[GT=tmnth]
SAVE /FILE=test.nc /CLOBBER mytime
SPAWN ncdump test.nc 
```
However, if the `T0="1-JAN-1970"` is changed to `T0="01-JAN-1970"`, then all is fine.  Using a regular axis defined by low:high:delta works fine with either T0 value.

Added bench/v7jnls/err75_time_origin.jnl test showing the error, but not yet run in any of the tests.

**Comment by AnsleyManke** [comment]
I'll take a look -

**Comment by AnsleyManke** [comment]
This is fixed in cd_write_axis.F

Ferret has always allowed dates to be put in as "1-JAN-1970" or "01-JAN-1970", stored them in that form, and converted them to time information as needed.  

With the change to allow the user to write dates as iso-8601 strings, we also allow "/T0=1970-01-01", and they can tell Ferret to write it in that form to netCDF files.  Either form is legal for the time origin within netCDF files in the CF standard.

This means a little more checking is done when writing dates in attributes to netCDF files, so "1-JAN-1970" is changed  to "01-JAN-1970" before and the code neglected to re-check the length of the date string before writing it.
