### ISSUE TITLE
parsing problem when abbreviating LET/TITLE with backquotes (immediate mode)

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1963]
I found this when trying to abbreviate the "LET/TITLE=" qualifier.  The following fails silently, without defining anything:

```
 	NOAA/PMEL TMAP
 	FERRET v7.52 (optimized)
 	Linux 2.6.32-754.23.1.el6.x86_64 64-bit - 12/03/19
 	11-Dec-19 17:08     

yes? let/t="title" a = sst[d=`1`]
yes? sho var
 Created by DEFINE VARIABLE:
```

Either adding one more letter to the "/TIME=" abbreviation, or removing the immediate-mode backquotes, allows the definition to occur:
```
yes? let/ti="title" a = sst[d=`1`]
yes? let/t="title" a = sst[d=1]
yes? sho var
 Created by DEFINE VARIABLE:
 >>> Definitions that replace any file variable of same name:
     A = SST[D=1]
         "title"
```

Abbreviating other qualifiers to one letter (like "/U=" for "/UNIT=") works fine.  Is Ferret perhaps trying to interpret "t=" as a time coordinate specification?  The following suggests that axis coordinates are not part of DEFINE VARIABLE, so that "/T=" ought to be interpreted as "/TITLE=":

```
yes? sho com def var
 DEFINE VARIABLE/TITLE/UNITS/QUIET/DATASET/BAD/REMOTE/LIKE
```

**Comment by AnsleyManke** [comment]
This seems to be in the command parsing.   Somehow the [d=`1`] grave-accent evaluation is throwing things off so that the code for "define variable" never even gets executed.

**Comment by AnsleyManke** [comment]
It looks as though the presence of a /T= is confusing the grave-accent parsing, which isn't aware of which command is being parsed, that is it doesn't know we're getting set to do a DEFINE VARIABLE.  It just wants to get the current context in which we're evaluating whatever is enclosed by the grave-accents.  And so it's saying well what are the qualifiers on the command-line?  There's a /T= on the command-line, so apply that.  Of course /t="title" isn't a valid time specification.  The command parser knows the command but the grave-accent evaluation may involve a whole stack of expressions.

Going back to old versions of Ferret, as far back as ferret_v672 and up through ferret_v7.4 the result would have been this:
```
yes? let/t="title" a = sst[d=`1`]
 **ERROR: command syntax: title
```
which is just as confusing, but at least stops the script.  We've made changes related to RETURN= and SHOW GRID and so forth which have to do with evaluating contexts, and which I believe account for the different behavior in v7.5 and higher. 

We could 
* During command parsing, expand LET/T= to the full LET/TITLE= in the stored command-line when qualifiers are identified, and before grave-accent expressions are evaluated. 

* Or, require abbreviations of 2 letters (Only when the qualifiers begin with region identifiers  I, J,... and X, Y,...  and we find a longer qualifier related to the command? ) 

These aren't completely explored. I'll think it through.

**Comment by AnsleyManke** [comment]
The real bug here was that an error message had gone missing.  In older versions of Ferret, we'd have seen this (somewhat unhelpful) message.

```
 yes? let/t="title" a = sst[d=`1`]
 **ERROR: command syntax: title
```

and we'd at least have been able to guess that there was something wrong with the /t="title".  I've found where that came in - it was in checking for iso-time date strings in a /T= specification. That is fixed. 

But also, Ferret has always treated the above when parsing the command and evaluating the grave-accent expression as if it's a /T= even though DEFINE VARIABLE doesn't have a /T= referring to time.

I've changed the parsing so that if a qualifier is written with just one letter, it's replaced with 4 letters - the length that's guaranteed to identify commands and qualifiers, so this becomes

```
yes? let/t="title" a = sst[d=`1`]
 !-> DEFINE VARIABLE/TITL="title" a = sst[d=1]
yes? show var
 Created by DEFINE VARIABLE:
 >>> Definitions that replace any file variable of same name:
     A = SST[D=1]
         "title"
```

By the way if a command has both /T= and /TITLE= then the qualifier that appears first in its list of qualifiers is the one used. For instance,
```

yes? show command list
 LIST/I/J/K/L/M/N/X/Y/Z/T/E/F/DATASET/HEADING/NOHEAD/SINGLY/FILE/APPEND
       /ORDER/FORMAT/TITLE/PRECISIO/RIGID/ILIMITS/JLIMITS/KLIMITS/LLIMITS
       /MLIMITS/NLIMITS/XLIMITS/YLIMITS/ZLIMITS/TLIMITS/ELIMITS/FLIMITS
       /CLOBBER/QUIET/WIDTH/EDGES/BOUNDS/NOBOUNDS/NOROWLAB/KEEP_AXI/NCFORMAT
       /XCHUNK/YCHUNK/ZCHUNK/TCHUNK/ECHUNK/FCHUNK/DEFLATE/SHUFFLE/ENDIAN
       /OUTTYPE/CURVILIN/LAYERZ/ASGLOBAL/STRLEN
```

has /T and /TITLE and /TLIMITS and /TCHUNK.  Using /T will be interpreted as being a time specifier.
