### ISSUE TITLE
Stereographic map projections don't work

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#31]
**Reported by sirott on 8 Jul 2000 17:02 UTC**
The following script:

use coads_climatology
set reg/l=1
set grid sst
go mp_stereographic_north
go mp_aspect
shade sst,x_page,y_page

creates a plot that is improperly scaled. See attached GIF.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/92

**Comment by karlmsmith** [comment]
**Comment by hankin@pmel.noaa.gov on 17 Jul 2000 16:53 UTC**
The latitude region must be specified for the polar stereographic projection to
work.

**Comment by karlmsmith** [comment]
**Comment by Jonathan.S.Callahan@noaa.gov on 21 Oct 2003 20:15 UTC**
Moving from the hankin@pmel.noaa.gov user to the Steven.C.Hankin@noaa.gov user.

**Comment by karlmsmith** [comment]
**Attachment from sirott@pmel.noaa.gov on 8 Jul 2000 17:03 UTC**
Bad polar sterographic plot
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_92_GIT_31/bad.gif

**Comment by karlmsmith** [comment]
**Attachment from sirott@pmel.noaa.gov on 8 Jul 2000 17:18 UTC**
Bad orthographic plot
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_92_GIT_31/bad_ortho.gif

**Comment by rodoulami** [comment]
The Stereographic map projections don't work when I use data other than the one provided in the Ferret demo.
Here's the error message it's giving at each try:

yes? use tmin.nc 
           *** NOTE: Units on axis "time" are not recognized: day as %y%m%d.%f
           *** NOTE: They will not be convertible:
yes? sh d
     currently SET data sets:
    1> ./tmin.nc  (default)
 name     title                             I         J         K         L
 TMIN     T2MIN[L=1,K=1]                   1:192     1:96      1:1       1:1
 
yes? SET REGION/X=0:360/Y=-90:00/L=1/k=1
yes? GO mp_stereographic_south 180 50
yes? GO mp_aspect
 **ERROR: illegal limits: "X_PAGE[I=@MAX,J=@MA..." does not exist at Y=-90:0
          Axis extremes are Y=0.5:1.E+08
DEFINE VARIABLE/quiet x_axis_range = `x_page[i=@max,j=@max]` - `x_page[i=@min,j=@min]`
Command file, command group, or REPEAT execution aborted

ANY HELP WILL BE APPRECIATED.
THANKS

**Comment by ACManke** [comment]
Did you include the command "set grid t2min" ? This tells the scripts which coordinate axes to use.  The simple script example is,

 
use coads_climatology 
go mp_stereographic_south
set grid sst
shade sst[l=1], x_page, y_page




If you do have a "set grid" command, then the message indicates that there may be something unexpected about in the variable's grid, so that the Y coordinates are not in the range -90:0.  More information about the units and range of the coordinates can be found with 

yes? show grid t2min

Also try looking at a basic 2-dimension plot of the variable:

yes? shade t2min


I also see  you have set a region with Y=-90:0, but you are sending a latitude of 50. I think that the script will still work, but maybe you want to specify -50.

**Comment by rodoulami** [comment]
Thanks @ACManke. It's now working.
