### ISSUE TITLE
`var,return=dsetpath`   gets the wrong dataset

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#400]
**Reported by @AnsleyManke on 21 Apr 2004 22:17 UTC**
d1.nc and d2.nc both have variables called temperature.
If we define a variable specifying a dataset number,
the result RETURN on this variable gives the default
data set, not the correct one.  Putting the specification
on the variable within the RETURN command works correctly.

 
yes? use d1
yes? use d2
 
yes? let u1 = temperature[d=1]
yes? say `u1,return=dsetpath`
  !-> MESSAGE/CONTINUE ./d2.nc
./d2.nc

yes? say `temperature[d=1], return=dsetpath`
 !-> MESSAGE/CONTINUE ./d1.nc
./d1.nc

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/853

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 5 Jan 2011 19:54 UTC**

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 26 Dec 2012 23:24 UTC**
A formatted, self-contained example:

```
 	NOAA/PMEL TMAP
 	FERRET v6.84  
 	Linux 2.6.32-279.14.1.el6.x86_64 64-bit - 12/18/12
 	26-Dec-12 18:20     

yes? use coads_climatology
yes? save/clob/file=a1.nc sst
 LISTing to file a1.nc
yes? save/clob/file=a2.nc sst
 LISTing to file a2.nc
yes? can dat/all; use a1; use a2
yes? let u1 = sst[say `u1,r=dsetpath`
 !-> MESSAGE/CONTINUE ./a2.nc
./a2.nc
yes? say `sst[d=1](d=1]
yes?),r=dsetpath`
 !-> MESSAGE/CONTINUE ./a1.nc
./a1.nc
```

**Comment by AnsleyManke** [comment]
I've used some of the logic from the SHOW VAR/TREE code to fix this, changing things ONLY for the case where the  variable definition contains [d=xx].  

In general "the dataset of a user-defined variable" is somewhat ambiguous.  The variable will be evaluated in the context of the current default dataset when an action is taken.  For a simple example, 

```
   yes? use etopo60
   yes? use etopo20

   yes? let terra = if rose gt 0 then rose
   yes? shade terra 
```

the variable "terra" will be assembled based on whichever dataset is the default when data is loaded.

However, if the definition contains a dataset number then it's clear that's the intent, so 

```
yes? use a1; use a2

yes? let u1 = sst[d=1]
yes? say `u1,r=dset`
 !-> MESSAGE/CONTINUE a1
./a1.nc

```

Otherwise leaving the return unchanged.  Need to add to the documentation about this.
