### ISSUE TITLE
Allow fortran formats for writing variables that include strings

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#950]
**Reported by @AnsleyManke on 15 Jul 2009 18:11 UTC**
Currently, writing variables that include string variables cannot be done by specifying a format:

```
yes? let a = {"aa","bbb", "cc"}
yes? let xx = {1,5,2}
yes? list/form=(a,f9.2) a,xx
             X: 0.5 to 3.5
 Column  1: A is {"aa","bbb", "cc"}
 Column  2: XX is {1,5,1}
 **ERROR: invalid command: format disallowed for multiple variables w/ strings
```

This is because of the logic involved in getting string variables out of memory and creating the line to output. See fer/gnl/list_multi_sub.F.  LIST/FORMAT= now just sends the variable to a Fortran WRITE statement. We would need to create  intermediate string variables, get the string out of memory, and send that along with any numeric variables to the WRITE statement.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1678

**Comment by AnsleyManke** [comment]
This was requested again recently.

I propose allowing this for simple format specifiers that have one Fortran specifier for each variable to be listed, no complicated ((3x, 2(f5.1, 2x, A7)) kinds of things.  Then just go through the variables and apply each single format to the corresponding variable, writing to an internal string, and then list that out for each record.   This would be in list_multi_sub.F

Of course once we do this, people will want more control than currently available in comma- and tab- separated output files.  There, it would be nice at least, to be able to write the string data without surrounding quotes.  That should be possible too; it'll need a little bit of new syntax, because /FORMAT is used both for /FORMAT=comma/FORMAT=(fortran-format-spec)

**Comment by AnsleyManke** [comment]
This is something I've wanted for a long time.  I've added both A formats for string data and also Integer formats, with some limitations.  So,  with the above definitions:

```
...
yes? list/form=(a4,f9.2, I7) a,xx, xx
             X: 0.5 to 3.5
 Column  1: A is {"aa","bbb", "cc"}
 Column  2: XX is {1,5,2}
 Column  3: XX is {1,5,2}
  aa     1.00      1
 bbb     5.00      5
  cc     2.00      2
```

But don't allow more complex formats, which would take a lot more work to implement

```
yes? let xy = xx + 8.2

yes? list/form=(a4, 3x, 2(1x,f6.3,)) a, xx, xy
 **ERROR: invalid command: Fortran format for list with strings must be one specifier per variable
```

This can be part of the upcoming Ferret v7.4 release, document as a beta capability.  It's self contained and doesn't change any existing behavior.
